version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/var/www/dist
    restart: always
